In [ ]:
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time
import re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import datetime

In [ ]:
# ChromeDriver 89.0.4389.82(공식 빌드) (64비트)

In [ ]:
Chrome_directory = 'chromedriver/chromedriver.exe' # 크롤링 코드를 돌리시려면 버전에 맞는 크롬드라이버를 다운로드해주시길 바랍니다.
driver = webdriver.Chrome(Chrome_directory)
options = webdriver.ChromeOptions()
options.add_argument('headless')    # 웹 브라우저를 띄우지 않는 headless chrome 옵션

In [ ]:
url = 'https://astro.kasi.re.kr/life/pageView/10?useElevation=1&lat=37.54980&lng=126.9671&elevation=0&output_range=1&date=2020-01-01&hour=&minute=&second=&address=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C'
driver.get(url)
# 페이지 소스 가져오기
html=driver.page_source
soup = BeautifulSoup(html)
time.sleep(2)

In [ ]:
start = '2014-01-01'
end = '2021-12-30'

In [ ]:
day =pd.date_range(start='2014-01-01', end='2021-10-30', freq='D') # 크롤링 날짜 범위 생성

In [ ]:
day.astype(str)[0]

'2014-01-01'

# 당진태양고도 크롤링

In [ ]:
# angle_1 = 방위각 , _2 = 고도 , _3 = 적경, _4 = 적위

In [ ]:
Chrome_directory = 'D:/02.users/wodud2468/chromedriver/chromedriver.exe'
driver = webdriver.Chrome(Chrome_directory)
options = webdriver.ChromeOptions()
date = []
hour = []
angle_1 = []
angle_2 = []
angle_3 = []
angle_4 = []
for d in day.astype(str):
    url = 'https://astro.kasi.re.kr/life/pageView/10?useElevation=1&lat=37.05127236188373&lng=126.51409076261092&elevation=-117.96642423355715&output_range=1&date={}&hour=13&minute=30&second=&address=%EC%B6%A9%EC%B2%AD%EB%82%A8%EB%8F%84+%EB%8B%B9%EC%A7%84%EC%8B%9C+%EC%84%9D%EB%AC%B8%EB%A9%B4+%EA%B5%90%EB%A1%9C%EA%B8%B8+30#'.format(d)
    driver.get(url)
    for i in range(1,25):
        date.append(d)
        hour.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[1]'.format(i)).text)
        angle_1.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[2]'.format(i)).text)
        angle_2.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[3]'.format(i)).text)
        angle_3.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[4]'.format(i)).text)
        angle_4.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[5]'.format(i)).text)

In [ ]:
df = pd.DataFrame([date,hour,angle_1,angle_2,angle_3,angle_4]).T
df.columns = ['date','hour','방위각','고도','적경','적위']

In [ ]:
# ./data/태양광/ 에 크롤링 완료된 데이터가 있습니다.
df.to_csv('dangjin_sun_height.csv')

# 울산태양고도 크롤링

In [ ]:
Chrome_directory = 'chromedriver/chromedriver.exe'
driver = webdriver.Chrome(Chrome_directory)
options = webdriver.ChromeOptions()
date = []
hour = []
angle_1 = []
angle_2 = []
angle_3 = []
angle_4 = []
for d in day.astype(str):
    url = 'https://astro.kasi.re.kr/life/pageView/10?useElevation=1&lat=19.694477084885456&lng=117.99260273191031&elevation=-113.52622118955425&output_range=1&date={}&hour=13&minute=30&second=&address=%EC%9A%B8%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C+%EB%82%A8%EA%B5%AC+%EC%9A%A9%EC%9E%A0%EB%A1%9C+623#'.format(d)
    driver.get(url)
    for i in range(1,25):
        date.append(d)
        hour.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[1]'.format(i)).text)
        angle_1.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[2]'.format(i)).text)
        angle_2.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[3]'.format(i)).text)
        angle_3.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[4]'.format(i)).text)
        angle_4.append(driver.find_element_by_xpath('//*[@id="sun-height-table"]/table/tbody/tr[{}]/td[5]'.format(i)).text)

In [ ]:
df2 = pd.DataFrame([date,hour,angle_1,angle_2,angle_3,angle_4]).T
df2.columns = ['date','hour','방위각','고도','적경','적위']

In [ ]:
# ./data/태양광/ 에 크롤링 완료된 데이터가 있습니다.
df2.to_csv('ulsan_sun_height.csv')